---
title: "SevereWeather"
author: "Gregory Smith"
date: "January 25, 2016"
output: html_document
---
Dependencies

```{r}
library(dplyr)
```

Download and extract data

```{r}
## check to see if file "RawData.csv" exists

if(!file.exists("./RawStormData.csv"))
{
    download.file("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2","./RawStormData.BZ2")
}
## downloaded file is stored as "./RawStormData.Bz2"
ExtractedData <- read.csv("RawStormData.BZ2")
```


# Exploring the data

## Start with Fatalities
```{r}
Fatalaties <- ExtractedData[,c(8,23)]

FatalSummation <- ddply(Fatalaties, .(EVTYPE), summarise, mean=mean(FATALITIES), sum=sum(FATALITIES))
# Limit Fatal Stats to those that have a total count > 0
LFatalSummation <- FatalSummation[FatalSummation$sum > 0 ,]
# Order by # of fatalities high to low
OrderLFatalSummation <- LFatalSummation[with(LFatalSummation, order(-LFatalSummation$sum)), ]

```

## Histogram of the events with the top 20 highest total fatalities
```{r}
LFatalSummation <- FatalSummation[FatalSummation$sum > 20 ,]
OrderLFatalSummation <- FatalSummation[FatalSummation$sum,order(-LFatalSummation$sum), ]

```


## Property damage is based on two columns "PROPDMG" a numeric value and "PROPDMGEXP" a letter value representing 
## K = 1000, M= 100000, 
```{r}

{```}